FROM node:22-alpine

ENV NODE_ENV=production

WORKDIR /usr/src/app

EXPOSE 4000

COPY package*.json ./

RUN npm ci --only=production --target_arch=x64 --target_platform=linux

COPY . .

CMD [ "npm", "start" ]
